app/__init__.py
from flask import Flask
from app.config import Config


def create_app(config_class=Config):

    app = Flask(__name__)
    app.config.from_object(Config)

    from app.main.routes import main
    app.register_blueprint(main)

    return app

app/main/routes.py
from flask import (
    render_template,
    Blueprint,
    send_from_directory,
    redirect,
    request,
    url_for,
    flash,
    Response,
    current_app
)
import smtplib
from email.message import EmailMessage
import ssl
from .utils import Utils
import os

main = Blueprint("main", __name__)


@main.route("/", methods=["GET"])
@main.route("/home", methods=["GET"])
def home():
    return render_template("home.html", title="Home")


@main.route("/resume")
def resume():
    return render_template("resume.html", title="Resume")


@main.route("/about")
def about():
    return render_template("about.html", title="About")


@main.route("/blog/<string:section>")
def blog(section):
    render = True
    
    match section:
        case "argentina":
            file_name = "blogs/International Economics Project 1.html"
        case "target":
            file_name = "blogs/target.html"
        case "energy_recovery":
            file_path = os.path.join(current_app.root_path, "templates", "blogs", "Energy Recovery.html")
            render = False
        case "home":
            file_name = "blog.html"

    if render: 
        return render_template(f"{file_name}", title="Blog")
    else: 
        with open(file_path, 'r') as file:
            raw_html = file.read()
        return Response(raw_html, mimetype='text/html')


@main.route("/projects")
def projects():
    return render_template("projects.html", title="Projects")


@main.route("/download-pdf")
def download_pdf():
    pdf_filename = "pdf/Samuel Adams Resume.pdf"
    return send_from_directory("static", pdf_filename, as_attachment=True)


@main.route("/render-table")
def render_table():
    balance_sheet_json = Utils.get_stock_data("TGT")
    return balance_sheet_json


@main.route("/email", methods=["POST"])
def form():
    if request.method == "POST":
        first_name = request.form.get("first-name")
        last_name = request.form.get("last-name")
        msg = f"""
            {first_name}
            {last_name}
            {request.form.get("message")}
        """
        email = "samuel.grant.adams@gmail.com"
        subject = "From you wesbite: Hello World!"

        em = EmailMessage()
        em["From"] = email
        em["To"] = email
        em["Subject"] = subject
        em.set_content(msg)

        context = ssl.create_default_context()
        HOST = os.getenv("HOST")
        SMTP_PORT = os.getenv("SMTP_PORT")
        SMTP_PASSWORD = os.getenv("SMTP_PORT")
        print(SMTP_PASSWORD)

        with smtplib.SMTP_SSL(HOST, SMTP_PORT, context=context) as server:
            # os.getenv("EMAIL_PASSWORD")
            server.login(email, SMTP_PASSWORD)
            server.sendmail(to_addrs=email, from_addr=email, msg=em.as_string())
            flash("Email sent to Sam!", "success")

        return redirect(url_for("main.home"))

app/templates/about.html
{% extends "layout.html" %}
{% block content %}

<title>{{ title }}</title>

<div class="about">
    <h1 class="text_shadows">The Long Haul</h1>
    <p>Oct 5</p>
    <p>
        I was born in Austin, Texas, the son of a game designer and a nurse. I find playing guitar more useful in life
        than many things I have learned in school.
        The intense feelings of satisfaction derived from the frustration of failing a song only to overcome is an
        experience everyone should strive to achieve.
        It is a solo instrument, and yet one that can and should require teamwork from time to time. It is easy to pick
        up, but incredibly arduous to master.
    </p>
    <p>
        I find art incredibly interesting, and the design, color, space, and overall context of a piece is like a puzzle
        for us to figure out.
        I also enjoy body building, another type of art that requires sculpture of the body.
        Crafting a body or mind takes grit, determination, and supreme confidence that you and only you can figure out
        the path.
    </p>
    <p>
        My life has been an experiment in cutting corners. To do what others think is not possible.
        I am not talented; I just have high standards. I am not smart; I am just curious. I am not lazy; I just work
        smart.
        I see things others may not notice from the outset. I see implications in actions that others may not see.
        Every action carries some consequence.
    </p>
    <p>
        Some things I have learned throughout my career as a financial engineer as an adaptation of Nike’s Ten
        Commandments:
    </p>
    <ul class="about-list">
        <li>1. Engineers may struggle with tiny defects.</li>
        <li>2. You must understand your own code.</li>
        <li>3. You are always a work in process.</li>
        <li>4. It will get ugly.</li>
        <li>5. Business is change, embrace it.</li>
        <li>6. Be scrappy.</li>
        <li>7. You know nothing.</li>
        <li>8. Money is means to an end, not the end.</li>
        <li>9. Never lie.</li>
        <li>10. Always give it your all.</li>
    </ul>

</div>


{% endblock content %}

app/templates/blog.html
{% extends "layout.html" %} {% block content %}

<div class="blog-container">
  <div class="main-header">Blogs</div>
  <div class="blog">
    <ul class="blog-content">
      <li>
        <a href="{{ url_for('main.blog', section='argentina') }}">
          Case Study of Argentina Default
        </a>
        <div class="blog-img">
          <img src="{{ url_for('static', filename='images/blogs/argentina/argentina_default.png') }}" alt="Argentina">
        </div>
      </li>
    </ul>
  </div>
  <div class="blog">
    <ul class="blog-content">
      <li>
        <a href="{{ url_for('main.blog', section='target') }}">
          Dive Into Target Post Pandemic
        </a>
        <div class="blog-img">
          <img src="{{ url_for('static', filename='images/blogs/target/target.png') }}" alt="Target">
        </div>
      </li>
    </ul>
  </div>
  <div class="blog">
    <ul class="blog-content">
      <li>
        <a href="{{ url_for('main.blog', section='energy_recovery') }}">
          Energy Recovery
        </a>
        <div class="blog-img">
          <img src="{{ url_for('static', filename='images/blogs/energy_recovery/energy_recovery.jpg') }}" alt="Energy Recovery">
        </div>
      </li>
    </ul>
  </div>
</div>

{% endblock %}

app/templates/home.html
{% extends "layout.html" %} {% block content %}

<div class="section">
  <!-- INTRO -->
  <div class="container" style="display: flex; flex-direction: column">
    <div class="main-title" style="margin: 0.5% 0">Sam Adams</div>
    <div class="main-header" style="margin: 0.5% 0">Financial Engineer 🧮</div>
    <div style="display: flex; flex-direction: row">
      <div class="pixel-container">
        <img
          class="pixel-image"
          src="{{ url_for('static', filename='images/intro/profile-pixel.jpg') }}"
        />
        <div class="pixel-overlay">
          <img
            src="{{ url_for('static', filename='images/intro/profile.jpg') }}"
          />
        </div>
      </div>
      <div style="margin: 0 2.5%; flex: 1">
        <div class="main-paragraph-text scrolling-text">
          I am a devoted aspiring financial engineer with a fervor for
          uncovering deep value and seizing alpha. "An investment in knowledge
          pays the best interest." - Ben Franklin
        </div>
      </div>
    </div>
  </div>

  <!-- ABOUT ME -->
  <div class="pixel-gallery">
    <div class="pixel-container">
      <div class="pixel-content">
        <img
          class="pixel-image"
          src="{{ url_for('static', filename='images/about/zach-bryan-pixel.webp') }}"
        />
        <div class="pixel-overlay">
          <img src="{{ url_for('static', filename='images/about/zach-bryan.webp') }}" />
        </div>
      </div>
      <div class="pixel-caption">
        <div>If you know you know</div>
      </div>
    </div>
    <div class="pixel-container">
      <div class="pixel-caption">The 512</div>
      <div class="pixel-content">
        <img
          class="pixel-image"
          src="{{ url_for('static', filename='images/about/austin-pixel.jpg') }}"
        />
        <div class="pixel-overlay">
          <img
            src="{{ url_for('static', filename='images/about/austin.jpg') }}"
          />
        </div>
      </div>
    </div>
    <div class="pixel-container">
      <div class="pixel-content">
        <img
          class="pixel-image"
          src="{{ url_for('static', filename='images/about/austin-postcard-pixel.jpg') }}"
        />
        <div class="pixel-overlay">
          <img
            src="{{ url_for('static', filename='images/about/austin-postcard.jpg') }}"
          />
        </div>
      </div>
      <div class="pixel-caption">Only the best city in Texas</div>
    </div>
  </div>
  <div class="container">
    <div class="main-divider"></div>
    <div class="main-header">My Core Values 🌟</div>
    <div class="scrolling-text">Integrity, Diligence, Curiosity</div>
    <div class="main-header">My Obsession with Computers 🖥️</div>
    <div style="width: 500px">
      <img
        class="shadow"
        src="{{ url_for('static', filename='images/about/computer.gif') }}"
        alt
      />
    </div>
    <div class="scrolling-text">
      Isn't it truly remarkable how computers can tackle immensely intricate
      problems in our contemporary world? I hold the firm belief that
      abstraction can enable the achievement of nearly any objective. The 21st
      century is undoubtedly the era of information, where financial markets
      stand entirely reliant on computers, and it's within our hands to
      determine whether the outcome is favorable or not. I possess the
      capability to craft original solutions for your company, even those you
      might not have realized you needed.
    </div>
  </div>

  <!-- CONTACT -->
  <div class="container" style="display: flex; flex-direction: row">
    <div style="width: 30%">
      <img
        src="{{ url_for('static', filename='images/connect/coffee.gif') }}"
        alt=""
      />
    </div>
    <div style="width: 70%">
      <div class="main-header">Lets Connect!</div>
      <div class="scrolling-text">
        Let's build something great together! My diverse skills and strategic
        approach help turn visions into robust, lasting solutions.
      </div>
    </div>
  </div>
  <div
    id="form-section"
    class="container"
    style="display: flex; flex-direction: column"
  >
    <div style="width: 20%">
      <img
        src="{{ url_for('static', filename='images/contact/paper-airplane.gif') }}"
        alt=""
      />
    </div>
    <div style="width: 100%">
      <form class="email-form" action="/email" method="post">
        <h1>Contact Me</h1>
        <div>
          <label for="first-name">First Name:</label>
          <input
            type="text"
            id="first-name"
            name="first-name"
            required
          /><br /><br />
        </div>
        <div>
          <label for="last-name">Last Name:</label>
          <input
            type="text"
            id="last-name"
            name="last-name"
            required
          /><br /><br />
        </div>
        <div><label for="message">Message:</label><br /></div>
        <textarea
          id="message"
          name="message"
          rows="4"
          cols="50"
          required
        ></textarea
        ><br /><br />

        <button class="button-54" type="submit" value="Submit">
          Send Email
        </button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="html">
  <head>
    <title>Sam Adams Personal Website</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='images/favicon.png') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/main.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/btn.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/pushbar.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/scrollbar.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/textgrow.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/loader.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/blog.css') }}"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/python-theme.css') }}"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/pushbar.js@1.0.0/src/pushbar.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/carousel.css') }}"
    />
  </head>

  <body>
    <aside data-pushbar-id="top" data-pushbar-direction="top">
      <div class="title"><span data-pushbar-close class="close">X</span></div>
      <ul class="menu">
        <li><a href="{{ url_for('main.home') }}">🏡 Home</a></li>
        <li><a href="{{ url_for('main.about') }}">👨🏻‍🎓 About</a></li>
        <li>
          <a href="{{ url_for('main.blog', section='home') }}">🖋️ Blog</a>
        </li>
        <li><a href="{{ url_for('main.projects') }}">🚧 Projects</a></li>
        <li><a href="{{ url_for('main.resume') }}">📓 Resume</a></li>
        <li>
          <a href="https://github.com/AdamsIncorporated" target="_blank"
            >🗃️ Github</a
          >
        </li>
      </ul>
    </aside>

    <div class="button-container">
      <button class="button-54" data-pushbar-target="top">Links</button>
    </div>

    {% with messages = get_flashed_messages() %} {% if messages %}
    <ul class="flashes">
      {% for message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %} {% endwith %}

    <main class="pushbar_main_content particle-container">
      {% block content %} {% endblock %}
    </main>

    <footer></footer>
  </body>

  <!-- Import Scripts -->
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="https://unpkg.com/scrollreveal"></script>
  <script src="https://cdn.jsdelivr.net/npm/pushbar.js@1.0.0/src/pushbar.min.js"></script>

  <!-- Source Scripts-->
  <script src="{{ url_for('static', filename='scripts/main.js') }}"></script>
  <script src="{{ url_for('static', filename='scripts/balance_sheet.js') }}"></script>
  <script src="{{ url_for('static', filename='scripts/particles.js') }}"></script>
</html>

app/templates/projects.html
{% extends "layout.html" %}
{% block content %}

Projects

{% endblock %}

app/templates/resume.html
{% extends "layout.html" %}
{% block content %}

<title>{{ title }}</title>

<div class="resume-button-container">
    <a href="{{ url_for('main.download_pdf') }}" class="button-54" download>
        <i class="fas fa-download"></i>
    </a>
</div>

<div class="resume">
    <h1 class="resume-title">Samuel Grant Adams</h1>
    <div class="social-media-icons">
        <div class="shadow"><img src="{{ url_for('static', filename='images/mail.jpg') }}" alt="Social Media Image">
        </div>
        <div class="shadow"><img src="{{ url_for('static', filename='images/facebook.jpg') }}" alt="Social Media Image">
        </div>
        <div class="shadow"><img src="{{ url_for('static', filename='images/instagram.png') }}"
                alt="Social Media Image"></div>
        <div class="shadow"><img src="{{ url_for('static', filename='images/linkedin.png') }}" alt="Social Media Image">
        </div>
    </div>
    <h1 class="resume-header">Financial Analyst</h1>
    <p>Well-motivated, self-driven, and service oriented. Strong analytical,
        quantitative, critical thinking and problem-solving skills.
        Proactive; internal drive to meet goals continuously and successfully.
        Solid
        grasp of tools for analyzing data. Ability to
        interface and communicate with all levels of staff and management.
        Demonstrated attention to detail, sense of urgency, and
        ability to learn quickly. Able to work within and meet aggressive
        deadlines
        in a fast paced, changing, high energy
        environment. High integrity. Core competencies:
    </p>

    <table class="resume-table">
        <tr>
            <td>DCF Modeling</td>
            <td>Equity Research</td>
            <td>Fixed-Income Analysis</td>
        </tr>
        <tr>
            <td>Data Science</td>
            <td>Dev Ops</td>
            <td>Natural Language Processing</td>
        </tr>
        <tr>
            <td>Texas Government Code</td>
            <td>Legislative Procedures</td>
            <td>Public Speaking</td>
        </tr>
    </table>

    <h2 class="resume-header">Education</h2>
    <div class="resume-date-row">
        <div>M.S., MSQFE; McCoy School of Business; Texas State University</div>
        <div>8/2022 – 5/2024</div>
    </div>
    <div class="resume-date-row">
        <div>B.S., Finance; The University of Texas at Dallas</div>
        <div>8/2018 – 5/2021</div>
    </div>

    <h2 class="resume-header">Professional Experience</h2>
    <div class="resume-date-row">
        <div class="resume-header2">Texas Bond Review Board</div>
        <div class="resume-header2">Austin, Texas</div>
    </div>
    <div class="resume-date-row">
        <p>Financial Analyst</p>
        <p>5/2022 – present</p>
    </div>

    <ul class="resume-list">
        <li>Crafted triggers, tables, and queries for smss Database</li>
        <li>Crafted Annual Report for Texas House of Legislature</li>
        <li>Crafted Flask web applications for bond counsel data portal and data visualization</li>
        <li>Curated SMSS SQL Database</li>
        <li>Created NLP software to extract data from web forms</li>
    </ul>
    <div class="resume-date-row">
        <div class="resume-header2">Municipal Advisory Council of Texas (M.A.C.) </div>
        <div class="resume-header2">Austin, Texas</div>
    </div>
    <div class="resume-date-row">
        <p>Financial Analyst</p>
        <p>4/2022 – 11/2022</p>
    </div>
    <ul class="resume-list">
        <li>Fixed-income, derivatives, and property analysis</li>
        <li>Automated key process from one year to single executable task</li>
        <li>Produced Texas Municipal Reports for public finance municipal market</li>
    </ul>
    <div class="resume-date-row">
        <div class="resume-header2">Binkley & Barfield, Inc</div>
        <div class="resume-header2">Houston, Texas</div>
    </div>
    <div class="resume-date-row">
        <p>Accounting Intern</p>
        <p>6/2021 – 4/2022</p>
    </div>
    <ul class="resume-list">
        <li>Increased efficiency of accounting cycle for payables with coding automation</li>
        <li>Processed invoices, collections, and financial reports</li>
        <li>Provided financial planning and analysis</li>
    </ul>
    <h2 class="resume-header">College Extracurriculars</h2>
    <ul class="resume-list">
        <li>CFA Challenge (MSQFE)</li>
        <li>President, University of Texas Financial Literacy Club</li>
        <li>Psi Zeta Chapter of the Chi Phi Fraternity</li>
        <li>Business Professional of America</li>
        <li>President of Toastmasters</li>
    </ul>

    <h2 class="resume-header">Community Experience</h2>
    <div class="resume-date-row">
        <div class="resume-header2">North Texas Entrepreneur Education and Training</div>
        <div>Dallas, Texas </div>
    </div>
    <div class="resume-date-row">
        <p>Volunteer Team Leader, Financial Budgeting and Forecasting</p>
        <p>5/2021 – 8/2021</p>
    </div>
    <ul class="resume-list">
        <li>Provided financial forecasting and accounting for projects. Prepare and analyze financial reports</li>
        <li>Collaborated with management on presenting financial statements to the City of Dallas</li>
        <li>Monitored and analyzed financial, statistical, and operational data trends</li>
    </ul>
    <h2 class="resume-header">Techinical Skills</h2>

    <h3 class="resume-sub-header">General Purpose</h3>
    <!-- General Production -->
    <div class="language-logos">
        <div><img src="{{ url_for('static', filename='images/language-logos/C.svg') }}" alt="Language Logo Image">
        </div>
        <div><img src="{{ url_for('static', filename='images/language-logos/C++.svg') }}" alt="Language Logo Image">
        </div>
        <div><img src="{{ url_for('static', filename='images/language-logos/C#.svg') }}" alt="Language Logo Image">
        </div>
        <div><img src="{{ url_for('static', filename='images/language-logos/Git.svg') }}" alt="Language Logo Image">
        </div>
        <div><img src="{{ url_for('static', filename='images/language-logos/Rust.svg') }}" alt="Language Logo Image">
        </div>
        <div><img src="{{ url_for('static', filename='images/language-logos/SQL.svg') }}" alt="Language Logo Image">
        </div>
        <div><img src="{{ url_for('static', filename='images/language-logos/VBA.svg') }}" alt="Language Logo Image">
        </div>
    </div>

    <h3 class="resume-sub-header">Web Development</h3>
    <!-- Web Languages -->
    <div class="language-logos">
        <div><img src="{{ url_for('static', filename='images/language-logos/JS.svg') }}" alt="Language Logo Image">
        </div>
        <div><img src="{{ url_for('static', filename='images/language-logos/TS.svg') }}" alt="Language Logo Image">
        </div>
        <div><img src="{{ url_for('static', filename='images/language-logos/HTML.svg') }}" alt="Language Logo Image">
        </div>
        <div><img src="{{ url_for('static', filename='images/language-logos/CSS.svg') }}" alt="Language Logo Image">
        </div>
    </div>

    <h3 class="resume-sub-header">Data Science</h3>
    <!-- Data Science -->
    <div class="language-logos">
        <div><img src="{{ url_for('static', filename='images/language-logos/Julia.svg') }}" alt="Language Logo Image">
        </div>
        <div><img src="{{ url_for('static', filename='images/language-logos/Scala.svg') }}" alt="Language Logo Image">
        </div>
        <div><img src="{{ url_for('static', filename='images/language-logos/Perl.svg') }}" alt="Language Logo Image">
        </div>
        <div><img src="{{ url_for('static', filename='images/language-logos/Python.svg') }}" alt="Language Logo Image">
        </div>
        <div><img src="{{ url_for('static', filename='images/language-logos/R.svg') }}" alt="Language Logo Image">
        </div>
    </div>

    <h3 class="resume-sub-header">Applications</h3>
    <!-- Apps -->
    <div class="language-logos">
        <div><img src="{{ url_for('static', filename='images/language-logos/Stata.svg') }}" alt="Language Logo Image">
        </div>
        <div><img src="{{ url_for('static', filename='images/language-logos/Tableau.svg') }}" alt="Language Logo Image">
        </div>
        <div><img src="{{ url_for('static', filename='images/language-logos/Photoshop.svg') }}"
                alt="Language Logo Image">
        </div>
        <div><img src="{{ url_for('static', filename='images/language-logos/Illustrator.svg') }}"
                alt="Language Logo Image">
        </div>
        <div><img src="{{ url_for('static', filename='images/language-logos/InDesign.svg') }}"
                alt="Language Logo Image">
        </div>
        <div><img src="{{ url_for('static', filename='images/language-logos/Excel.svg') }}" alt="Language Logo Image">
        </div>
        <div><img src="{{ url_for('static', filename='images/language-logos/Power BI.svg') }}"
                alt="Language Logo Image">
        </div>
    </div>

    <h2 class="resume-header">Professional Designations</h2>
    <ul class="resume-list">
        <li>SIE</li>
        <li>Series 63</li>
    </ul>
</div>

{% endblock %}